### ISSUE TITLE
LetterBoxE32_ATTINY.ino - no power saving code

### ISSUE THREAD

**Issue by maddog75** [SensorsIot/LoRa_Mailbux_Notifier#1]
Hi,

Have I missed something, or is there no sleep mode code in this file?

**Comment by SensorsIot** [comment]
You are right. I said in the video that I have to add it

**Comment by SensorsIot** [comment]
Now, you can take a look at the new code. It took quite some time to understand how sleep and interrupts work on the ATTINY. Currently, the ATTINY and the E32 consume 28 microamperes @ 3V during sleep (38 micros @ 3.3V).

4.7k pullup resistor and a 0.2 microfarad cap are needed for the switches (even if I used INPUT_PULLUP)
